package state

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// State represents the installation state
type State struct {
	AgentID           string            `json:"agent_id,omitempty"`          // Agent ID (UUID) generated by backend
	AgentName         string            `json:"agent_name,omitempty"`        // Agent name (user-provided)
	RegistrationTime  time.Time         `json:"registration_time,omitempty"` // When agent was registered
	Phase             Phase             `json:"phase"`                       // current|k3s|calico|liqo|peering|offloading|complete|failed
	LastUpdated       time.Time         `json:"last_updated"`                // Last state update timestamp
	RollbackAvailable bool              `json:"rollback_available"`          // Whether rollback is available
	Checkpoints       []Checkpoint      `json:"checkpoints"`                 // Installation checkpoints
	LastError         *ErrorInfo        `json:"last_error,omitempty"`        // Last error information
	Versions          map[string]string `json:"versions,omitempty"`          // Component versions used at register
	// RegisterScope stores register flags needed by standalone cluster verify.
	RegisterScope *RegisterScope `json:"register_scope,omitempty"`
}

// RegisterScope is the subset of register flags that affect post-install verify.
type RegisterScope struct {
	DisableOffloading   bool     `json:"disable_offloading,omitempty"`
	SkipOperatorInstall bool     `json:"skip_operator_install,omitempty"`
	HypervisorDriver    string   `json:"hypervisor_driver,omitempty"`
	OperatorNamespace   string   `json:"operator_namespace,omitempty"` // optional offload ns
	VNCGatewayNamespace string   `json:"vnc_gateway_namespace,omitempty"`
	OffloadNamespaces   []string `json:"offload_namespaces,omitempty"`
}

// Checkpoint represents an installation checkpoint
type Checkpoint struct {
	Phase        Phase            `json:"phase"`                   // k3s|calico|liqo|peering|offloading
	Timestamp    time.Time        `json:"timestamp"`               // Checkpoint creation time
	Status       CheckpointStatus `json:"status"`                  // success|failed
	SnapshotPath string           `json:"snapshot_path,omitempty"` // Optional snapshot path
}

// ErrorInfo represents error information
type ErrorInfo struct {
	Phase       Phase     `json:"phase"`
	Timestamp   time.Time `json:"timestamp"`
	Error       string    `json:"error"`
	Recoverable bool      `json:"recoverable"`
}

// Manager manages installation state
type Manager struct {
	statePath string
	state     *State
}

// NewManager creates a new state manager
// agentID can be either the agent ID (UUID) or agent name
func NewManager(configDir, agentID string) *Manager {
	stateDir := filepath.Join(configDir, "clusters", agentID)
	statePath := filepath.Join(stateDir, "state.json")

	return &Manager{
		statePath: statePath,
		state: &State{
			Phase:             PhaseCurrent,
			LastUpdated:       time.Now(),
			RollbackAvailable: false,
			Checkpoints:       []Checkpoint{},
		},
	}
}

// SetAgentInfo sets agent ID and name
func (m *Manager) SetAgentInfo(agentID, agentName string) {
	m.state.AgentID = agentID
	m.state.AgentName = agentName
	if m.state.RegistrationTime.IsZero() {
		m.state.RegistrationTime = time.Now()
	}
}

// GetAgentID returns the agent ID
func (m *Manager) GetAgentID() string {
	return m.state.AgentID
}

// GetAgentName returns the agent name
func (m *Manager) GetAgentName() string {
	return m.state.AgentName
}

// Load loads state from file
func (m *Manager) Load() error {
	data, err := os.ReadFile(m.statePath)
	if err != nil {
		if os.IsNotExist(err) {
			// No state file exists, use default state
			return nil
		}
		return fmt.Errorf("read state file: %w", err)
	}

	if err := json.Unmarshal(data, &m.state); err != nil {
		return fmt.Errorf("unmarshal state: %w", err)
	}

	return nil
}

// Save saves state to file
func (m *Manager) Save() error {
	// Ensure directory exists
	dir := filepath.Dir(m.statePath)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create state directory: %w", err)
	}

	m.state.LastUpdated = time.Now()

	data, err := json.MarshalIndent(m.state, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal state: %w", err)
	}

	if err := os.WriteFile(m.statePath, data, 0600); err != nil {
		return fmt.Errorf("write state file: %w", err)
	}

	return nil
}

// GetState returns the current state
func (m *Manager) GetState() *State {
	return m.state
}

// SetPhase sets the current installation phase
func (m *Manager) SetPhase(phase Phase) {
	m.state.Phase = phase
}

// AddCheckpoint adds a new checkpoint
func (m *Manager) AddCheckpoint(phase Phase, status CheckpointStatus, snapshotPath string) {
	checkpoint := Checkpoint{
		Phase:        phase,
		Timestamp:    time.Now(),
		Status:       status,
		SnapshotPath: snapshotPath,
	}
	m.state.Checkpoints = append(m.state.Checkpoints, checkpoint)
	m.state.RollbackAvailable = true
}

// SetError sets the last error information
func (m *Manager) SetError(phase Phase, errorMsg string, recoverable bool) {
	m.state.LastError = &ErrorInfo{
		Phase:       phase,
		Timestamp:   time.Now(),
		Error:       errorMsg,
		Recoverable: recoverable,
	}
	m.state.Phase = PhaseFailed
}

// ClearError clears the last error
func (m *Manager) ClearError() {
	m.state.LastError = nil
}

// GetLastCheckpoint returns the last successful checkpoint
func (m *Manager) GetLastCheckpoint() *Checkpoint {
	for i := len(m.state.Checkpoints) - 1; i >= 0; i-- {
		if m.state.Checkpoints[i].Status == CheckpointStatusSuccess {
			return &m.state.Checkpoints[i]
		}
	}
	return nil
}

// HasSuccessfulCheckpoint reports whether a phase completed successfully.
func (m *Manager) HasSuccessfulCheckpoint(phase Phase) bool {
	for _, cp := range m.state.Checkpoints {
		if cp.Phase == phase && cp.Status == CheckpointStatusSuccess {
			return true
		}
	}
	return false
}

// ClearCheckpoints removes all checkpoints for the given phase.
func (m *Manager) ClearCheckpoints(phase Phase) {
	out := m.state.Checkpoints[:0]
	for _, cp := range m.state.Checkpoints {
		if cp.Phase != phase {
			out = append(out, cp)
		}
	}
	m.state.Checkpoints = out
	m.state.RollbackAvailable = len(out) > 0
}

// CanResume checks if installation can be resumed
func (m *Manager) CanResume() bool {
	return m.state.Phase != PhaseComplete && m.state.Phase != PhaseCurrent && m.state.LastError != nil && m.state.LastError.Recoverable
}

// SetVersions stores component versions used during registration.
func (m *Manager) SetVersions(versions map[string]string) {
	if versions == nil {
		return
	}
	if m.state.Versions == nil {
		m.state.Versions = map[string]string{}
	}
	for k, v := range versions {
		m.state.Versions[k] = v
	}
}

// SetRegisterScope persists register flags for standalone verify.
func (m *Manager) SetRegisterScope(scope RegisterScope) {
	cp := scope
	// Copy the slice so a caller's cobra flag value cannot mutate persisted state.
	cp.OffloadNamespaces = append([]string(nil), scope.OffloadNamespaces...)
	m.state.RegisterScope = &cp
}

// GetRegisterScope returns persisted register flags, if any.
func (m *Manager) GetRegisterScope() *RegisterScope {
	return m.state.RegisterScope
}

// StateDir returns the cluster state directory.
func (m *Manager) StateDir() string {
	return filepath.Dir(m.statePath)
}

// StatePath returns the path to state.json.
func (m *Manager) StatePath() string {
	return m.statePath
}

// Backup copies state.json to a timestamped backup beside it.
func (m *Manager) Backup() (string, error) {
	if _, err := os.Stat(m.statePath); err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	backupPath := filepath.Join(m.StateDir(), fmt.Sprintf("state.backup-%d.json", time.Now().Unix()))
	data, err := os.ReadFile(m.statePath)
	if err != nil {
		return "", err
	}
	//nolint:gosec // G703: backup path is under the CLI-managed state directory
	if err := os.WriteFile(backupPath, data, 0600); err != nil {
		return "", err
	}
	return backupPath, nil
}

// ClearLocalState removes the cluster state directory.
func (m *Manager) ClearLocalState() error {
	dir := m.StateDir()
	if dir == "" || dir == "." || dir == "/" {
		return fmt.Errorf("refusing to remove unsafe state directory: %q", dir)
	}
	return os.RemoveAll(dir)
}

// ResetCheckpoints clears checkpoints and error while preserving agent identity.
func (m *Manager) ResetCheckpoints() {
	m.state.Checkpoints = []Checkpoint{}
	m.state.RollbackAvailable = false
	m.state.LastError = nil
	if m.state.Phase == PhaseFailed {
		m.state.Phase = PhaseCurrent
	}
}

// RollbackToLastCheckpoint truncates checkpoints after the last success and sets phase to it.
func (m *Manager) RollbackToLastCheckpoint() (*Checkpoint, error) {
	last := m.GetLastCheckpoint()
	if last == nil {
		return nil, fmt.Errorf("no successful checkpoint to roll back to")
	}

	trimmed := make([]Checkpoint, 0, len(m.state.Checkpoints))
	for _, cp := range m.state.Checkpoints {
		trimmed = append(trimmed, cp)
		if cp.Phase == last.Phase && cp.Status == CheckpointStatusSuccess && cp.Timestamp.Equal(last.Timestamp) {
			break
		}
	}
	m.state.Checkpoints = trimmed
	m.state.Phase = last.Phase
	m.state.LastError = nil
	m.state.RollbackAvailable = len(trimmed) > 0
	return last, nil
}

// ReconcilePhase updates phase based on detected installed components.
func ReconcilePhase(k3sOK, calicoOK, liqoOK, peeringOK, complete bool) Phase {
	switch {
	case complete:
		return PhaseComplete
	case peeringOK:
		return PhasePeering
	case liqoOK:
		return PhaseLiqo
	case calicoOK:
		return PhaseCalico
	case k3sOK:
		return PhaseK3s
	default:
		return PhaseCurrent
	}
}
